//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TibiaTools.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TibiaDatabase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TibiaDatabase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TibiaTools.Database.TibiaDatabase", typeof(TibiaDatabase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Abyss Hammer,20000,
        ///2,Abyssador&apos;s Lash,,
        ///3,Acorn,,
        ///4,Albino Plate,,
        ///5,Alloy Legs,11000,
        ///6,Amazon Armor,,
        ///7,Amazon Helmet,,
        ///8,Amazon Shield,,
        ///9,Amber Staff,8000,
        ///10,Amphora,,
        ///11,Amulet of Loss,,
        ///12,Ancient Amulet,200,
        ///13,Ancient Belt Buckle,260,
        ///14,Ancient Coin,350,
        ///15,Ancient Shield,900,
        ///16,Ancient Stone,200,
        ///17,Ancient Tiara,,
        ///18,Ancient Watch,,
        ///19,Angelic Axe,5000,
        ///20,Ankh,,
        ///21,Antlers,50,0.90
        ///22,Ape Fur,,1.2
        ///23,Arbalest,,
        ///24,Arcane Staff,,
        ///25,Arrow,,
        ///26,Assassin Dagger,20000,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemDatabase {
            get {
                return ResourceManager.GetString("ItemDatabase", resourceCulture);
            }
        }
    }
}
