//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TibiaTools.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TibiaTools.Application.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia Tools is an Open Source project. All the application and source code can be find in:.
        /// </summary>
        internal static string AboutSourceCodeIn {
            get {
                return ResourceManager.GetString("AboutSourceCodeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aditional gold by unsplited items.
        /// </summary>
        internal static string AditionalValueByUnsplitedItems {
            get {
                return ResourceManager.GetString("AditionalValueByUnsplitedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Players Deaths (soon!).
        /// </summary>
        internal static string ButtonLastPlayersDeath {
            get {
                return ResourceManager.GetString("ButtonLastPlayersDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Counter and Splitter.
        /// </summary>
        internal static string ButtonLootSplitter {
            get {
                return ResourceManager.GetString("ButtonLootSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one of bellow tools:.
        /// </summary>
        internal static string ChooseOneBellowTools {
            get {
                return ResourceManager.GetString("ChooseOneBellowTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list is empty..
        /// </summary>
        internal static string EmptyPlayerItemList {
            get {
                return ResourceManager.GetString("EmptyPlayerItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works:
        ///
        ///This funcionality is based on online players, so it search player by player and returns all player deaths of the selected world in the last 3 hours. This tool can be useful to check if there are kicks or freezes on server.
        /// </summary>
        internal static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use:.
        /// </summary>
        internal static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check the readme file on project GitHub page:.
        /// </summary>
        internal static string HowToUseReadMe {
            get {
                return ResourceManager.GetString("HowToUseReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt PAID, but without profit or waste..
        /// </summary>
        internal static string HuntPaid {
            get {
                return ResourceManager.GetString("HuntPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each member will recive {0} gps as individual profit..
        /// </summary>
        internal static string IndividualProfit {
            get {
                return ResourceManager.GetString("IndividualProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each member lost {0} gps as individual waste..
        /// </summary>
        internal static string IndividualWaste {
            get {
                return ResourceManager.GetString("IndividualWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert all the loot (use look action on items).
        /// </summary>
        internal static string InsertPlayerLoot {
            get {
                return ResourceManager.GetString("InsertPlayerLoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the player quantity:.
        /// </summary>
        internal static string InsertPlayerQuantity {
            get {
                return ResourceManager.GetString("InsertPlayerQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items that was not possible to split between the players:.
        /// </summary>
        internal static string ItemsUnsplited {
            get {
                return ResourceManager.GetString("ItemsUnsplited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to player that wasted {0} gps..
        /// </summary>
        internal static string ItensToPlayerWasted {
            get {
                return ResourceManager.GetString("ItensToPlayerWasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to player that wasted {0} gps.
        ///As does not be possible to split some items, this player need to reicive an additional of {1} gps..
        /// </summary>
        internal static string ItensToPlayerWastedAditional {
            get {
                return ResourceManager.GetString("ItensToPlayerWastedAditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string LanguageStr {
            get {
                return ResourceManager.GetString("LanguageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Players Deaths.
        /// </summary>
        internal static string LastPlayersDeaths {
            get {
                return ResourceManager.GetString("LastPlayersDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Counter and Splitter - Result.
        /// </summary>
        internal static string LootSplitterResult {
            get {
                return ResourceManager.GetString("LootSplitterResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Counter and Splitter - Step 1.
        /// </summary>
        internal static string LootSplitterStepOne {
            get {
                return ResourceManager.GetString("LootSplitterStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Counter and Splitter - Step 2.
        /// </summary>
        internal static string LootSplitterStepTwo {
            get {
                return ResourceManager.GetString("LootSplitterStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} gold spent:.
        /// </summary>
        internal static string MoneySpentPlayerNun {
            get {
                return ResourceManager.GetString("MoneySpentPlayerNun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (1 Item).
        /// </summary>
        internal static string OneItem {
            get {
                return ResourceManager.GetString("OneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select game world:.
        /// </summary>
        internal static string SelectWorld {
            get {
                return ResourceManager.GetString("SelectWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a game world and start.
        /// </summary>
        internal static string SelectWorldAndStart {
            get {
                return ResourceManager.GetString("SelectWorldAndStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your configuration was saved succefull!.
        /// </summary>
        internal static string SuccefullSavedConfig {
            get {
                return ResourceManager.GetString("SuccefullSavedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFIT! Total profit was {0} gps!.
        /// </summary>
        internal static string TotalProfit {
            get {
                return ResourceManager.GetString("TotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value.
        /// </summary>
        internal static string TotalValue {
            get {
                return ResourceManager.GetString("TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value obtained: {0} gps..
        /// </summary>
        internal static string TotalValueObtained {
            get {
                return ResourceManager.GetString("TotalValueObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value spent: {0} gps..
        /// </summary>
        internal static string TotalValueSpent {
            get {
                return ResourceManager.GetString("TotalValueSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASTE! Total waste was {0} gps!.
        /// </summary>
        internal static string TotalWaste {
            get {
                return ResourceManager.GetString("TotalWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to pay to another player.
        /// </summary>
        internal static string ValueMemberNeedToPayToAnother {
            get {
                return ResourceManager.GetString("ValueMemberNeedToPayToAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to recive from another player.
        /// </summary>
        internal static string ValueMemberNeedToReciveAnother {
            get {
                return ResourceManager.GetString("ValueMemberNeedToReciveAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of each {0}:.
        /// </summary>
        internal static string ValueOfItem {
            get {
                return ResourceManager.GetString("ValueOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} Items).
        /// </summary>
        internal static string XItems {
            get {
                return ResourceManager.GetString("XItems", resourceCulture);
            }
        }
    }
}
